# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170107_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item',
            field=models.CharField(max_length=120),
        ),
    ]
